FROM node:20-alpine3.18 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Thêm các ARG để nhận biến khi build
ARG NEXT_PUBLIC_API_URL_SOCKET
ARG NEXT_PUBLIC_API_URL_CHATTING
ARG NEXT_PUBLIC_API_URL_MARKETING
ARG NEXT_PUBLIC_API_URL_USER
ARG NEXT_PUBLIC_API_URL_CHAT_BOT
ARG NEXT_PUBLIC_API_URL_PAYMENT

# Set environment variables cho build time
ENV NEXT_PUBLIC_API_URL_SOCKET=$NEXT_PUBLIC_API_URL_SOCKET
ENV NEXT_PUBLIC_API_URL_CHATTING=$NEXT_PUBLIC_API_URL_CHATTING
ENV NEXT_PUBLIC_API_URL_MARKETING=$NEXT_PUBLIC_API_URL_MARKETING
ENV NEXT_PUBLIC_API_URL_USER=$NEXT_PUBLIC_API_URL_USER
ENV NEXT_PUBLIC_API_URL_CHAT_BOT=$NEXT_PUBLIC_API_URL_CHAT_BOT
ENV NEXT_PUBLIC_API_URL_PAYMENT=$NEXT_PUBLIC_API_URL_PAYMENT

RUN npm run build

FROM node:20-alpine3.18
WORKDIR /app

COPY --from=builder /app ./

# Set lại environment variables cho runtime
ENV NEXT_PUBLIC_API_URL_SOCKET=$NEXT_PUBLIC_API_URL_SOCKET
ENV NEXT_PUBLIC_API_URL_CHATTING=$NEXT_PUBLIC_API_URL_CHATTING
ENV NEXT_PUBLIC_API_URL_MARKETING=$NEXT_PUBLIC_API_URL_MARKETING
ENV NEXT_PUBLIC_API_URL_USER=$NEXT_PUBLIC_API_URL_USER
ENV NEXT_PUBLIC_API_URL_CHAT_BOT=$NEXT_PUBLIC_API_URL_CHAT_BOT
ENV NEXT_PUBLIC_API_URL_PAYMENT=$NEXT_PUBLIC_API_URL_PAYMENT

EXPOSE 3000
CMD ["npm", "run", "start"]