services:
  mysql:
    image: mysql:latest
    container_name: chatting_database_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - my-mysql-data:/var/lib/mysql
      - ./chatting.sql:/docker-entrypoint-chattingdb.d/chatting.sql  # Cấu hình khởi tạo cơ sở dữ liệu
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin -u root -p${MYSQL_ROOT_PASSWORD} ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  your-app:
    build:
      context: .
    image: devhuynh2003/chatting-server:latest
    container_name: chatting-server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8082:8082"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network


volumes:
  my-mysql-data:
networks:
  app-network:
    driver: bridge
